from django.urls import path
from . import views

urlpatterns = [
    # Dashboard & Auth
    path('', views.index, name='admin_index'),
    path('index', views.index),
    path('index.php', views.index),
    path('dashboard-live-data', views.dashboard_live_data),
    path('dashboard-live-data.php', views.dashboard_live_data),
    path('login', views.login_view, name='admin_login'),
    path('login.php', views.login_view),
    path('login-check', views.login_check),
    path('login-check.php', views.login_check),
    path('logout', views.logout_view, name='admin_logout'),
    path('logout.php', views.logout_view),
    path('signup', views.signup_view, name='admin_signup'),
    path('signup.php', views.signup_view),
    path('forget', views.forget_view, name='admin_forget'),
    path('forget.php', views.forget_view),

    # Admin Management
    path('manage-admin', views.manage_admin, name='manage_admin'),
    path('manage-admin.php', views.manage_admin),
    path('add-admin', views.add_admin, name='add_admin'),
    path('add-admin.php', views.add_admin),
    path('add-admin-handler', views.add_admin_handler),
    path('add-admin-handler.php', views.add_admin_handler),
    path('update-admin', views.update_admin, name='update_admin'),
    path('update-admin.php', views.update_admin),
    path('update-password', views.update_password, name='update_password'),
    path('update-password.php', views.update_password),
    path('delete-admin', views.delete_admin, name='delete_admin'),
    path('delete-admin.php', views.delete_admin),

    # Category Management
    path('manage-category', views.manage_category, name='manage_category'),
    path('manage-category.php', views.manage_category),
    path('add-category', views.add_category, name='add_category'),
    path('add-category.php', views.add_category),
    path('update-category', views.update_category, name='update_category'),
    path('update-category.php', views.update_category),
    path('delete-category', views.delete_category, name='delete_category'),
    path('delete-category.php', views.delete_category),

    # Food Management
    path('manage-food', views.manage_food, name='manage_food'),
    path('manage-food.php', views.manage_food),
    path('add-food', views.add_food, name='add_food'),
    path('add-food.php', views.add_food),
    path('update-food', views.update_food, name='update_food'),
    path('update-food.php', views.update_food),
    path('delete-food', views.delete_food, name='delete_food'),
    path('delete-food.php', views.delete_food),

    # Inventory
    path('inventory', views.inventory, name='inventory'),
    path('inventory.php', views.inventory),
    path('update-inventory', views.update_inventory, name='update_inventory'),
    path('update-inventory.php', views.update_inventory),

    # Online Orders
    path('manage-online-order', views.manage_online_order, name='manage_online_order'),
    path('manage-online-order.php', views.manage_online_order),
    path('update-online-order', views.update_online_order, name='update_online_order'),
    path('update-online-order.php', views.update_online_order),
    path('manage-repeat-rate', views.manage_repeat_rate, name='manage_repeat_rate'),
    path('manage-repeat-rate.php', views.manage_repeat_rate),

    # Eat-In / User Management
    path('manage-ei-order', views.manage_ei_order, name='manage_ei_order'),
    path('manage-ei-order.php', views.manage_ei_order),
    path('update-ei-order', views.update_ei_order, name='update_ei_order'),
    path('update-ei-order.php', views.update_ei_order),
    path('delete-ei-order', views.delete_ei_order, name='delete_ei_order'),
    path('delete-ei-order.php', views.delete_ei_order),
    path('process-payment', views.process_payment),
    path('process-payment.php', views.process_payment),
    path('update-user-role', views.update_user_role, name='update_user_role'),
    path('update-user-role.php', views.update_user_role),

    # Restaurant Vendor Approvals
    path('manage-restro', views.manage_restro, name='manage_restro'),
    path('manage-restro.php', views.manage_restro),
    path('update-restro-status', views.update_restro_status, name='update_restro_status'),
    path('update-restro-status.php', views.update_restro_status),
    path('manage-restro-category', views.manage_restro_category, name='manage_restro_category'),
    path('manage-restro-category.php', views.manage_restro_category),
    path('update-restro-category', views.update_restro_category, name='update_restro_category'),
    path('update-restro-category.php', views.update_restro_category),
    path('manage-restro-food', views.manage_restro_food, name='manage_restro_food'),
    path('manage-restro-food.php', views.manage_restro_food),
    path('update-restro-food', views.update_restro_food, name='update_restro_food'),
    path('update-restro-food.php', views.update_restro_food),
    path('manage-restro-review', views.manage_restro_review, name='manage_restro_review'),
    path('manage-restro-review.php', views.manage_restro_review),

    # Delivery Boy
    path('manage-delivery-boy', views.manage_delivery_boy, name='manage_delivery_boy'),
    path('manage-delivery-boy.php', views.manage_delivery_boy),
    path('verify-delivery-boy', views.verify_delivery_boy, name='verify_delivery_boy'),
    path('verify-delivery-boy.php', views.verify_delivery_boy),
    path('delete-delivery-boy', views.delete_delivery_boy, name='delete_delivery_boy'),
    path('delete-delivery-boy.php', views.delete_delivery_boy),
    path('update-delivery-boy-status', views.update_delivery_boy_status, name='update_delivery_boy_status'),
    path('update-delivery-boy-status.php', views.update_delivery_boy_status),

    # Coupons
    path('manage-coupons', views.manage_coupons, name='manage_coupons'),
    path('manage-coupons.php', views.manage_coupons),
    path('add-coupon', views.add_coupon, name='add_coupon'),
    path('add-coupon.php', views.add_coupon),
    path('update-coupon', views.update_coupon, name='update_coupon'),
    path('update-coupon.php', views.update_coupon),
    path('delete-coupon', views.delete_coupon, name='delete_coupon'),
    path('delete-coupon.php', views.delete_coupon),
    path('manage-fest-coupon', views.manage_fest_coupon, name='manage_fest_coupon'),
    path('manage-fest-coupon.php', views.manage_fest_coupon),
    path('add-fest-coupon', views.add_fest_coupon, name='add_fest_coupon'),
    path('add-fest-coupon.php', views.add_fest_coupon),
    path('update-fest-coupon', views.update_fest_coupon, name='update_fest_coupon'),
    path('update-fest-coupon.php', views.update_fest_coupon),
    path('delete-fest-coupon', views.delete_fest_coupon, name='delete_fest_coupon'),
    path('delete-fest-coupon.php', views.delete_fest_coupon),

    # History & Feedback
    path('monthly-revenue', views.monthly_revenue, name='monthly_revenue'),
    path('monthly-revenue.php', views.monthly_revenue),
    path('manage-delivery-payment', views.manage_delivery_payment, name='manage_delivery_payment'),
    path('manage-delivery-payment.php', views.manage_delivery_payment),
    path('manage-review', views.manage_review, name='manage_review'),
    path('manage-review.php', views.manage_review),
    path('messages', views.messages, name='messages'),
    path('messages.php', views.messages),
    path('read-message', views.read_message, name='read_message'),
    path('read-message.php', views.read_message),
    path('delete-message', views.delete_message, name='delete_message'),
    path('delete-message.php', views.delete_message),
]
